// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.
import * as React from 'react';
import Svg, {Defs, LinearGradient, Stop, Path, Circle} from 'react-native-svg';

function SvgComponent(size = 100) {
    return (
        <Svg
            id='Layer_1'
            data-name='Layer 1'
            viewBox='0 0 1105.11 1105.74'
            height={size}
            width={size}
        >
            <Defs>
                <LinearGradient
                    id='linear-gradient'
                    x1={606.67}
                    y1={623.1}
                    x2={1037.65}
                    y2={1005.06}
                    gradientUnits='userSpaceOnUse'
                >
                    <Stop
                        offset={0}
                        stopColor='#5e17eb'
                    />
                    <Stop
                        offset={0}
                        stopColor='#5e17eb'
                    />
                    <Stop
                        offset={0.01}
                        stopColor='#5e17ea'
                    />
                    <Stop
                        offset={0.01}
                        stopColor='#5e17ea'
                    />
                    <Stop
                        offset={0.02}
                        stopColor='#5e17e9'
                    />
                    <Stop
                        offset={0.02}
                        stopColor='#5e17e9'
                    />
                    <Stop
                        offset={0.02}
                        stopColor='#5d17e8'
                    />
                    <Stop
                        offset={0.03}
                        stopColor='#5d18e8'
                    />
                    <Stop
                        offset={0.03}
                        stopColor='#5d18e7'
                    />
                    <Stop
                        offset={0.04}
                        stopColor='#5d18e6'
                    />
                    <Stop
                        offset={0.04}
                        stopColor='#5d18e6'
                    />
                    <Stop
                        offset={0.04}
                        stopColor='#5d18e5'
                    />
                    <Stop
                        offset={0.05}
                        stopColor='#5d18e5'
                    />
                    <Stop
                        offset={0.05}
                        stopColor='#5d18e4'
                    />
                    <Stop
                        offset={0.05}
                        stopColor='#5c18e4'
                    />
                    <Stop
                        offset={0.06}
                        stopColor='#5c18e3'
                    />
                    <Stop
                        offset={0.06}
                        stopColor='#5c18e3'
                    />
                    <Stop
                        offset={0.07}
                        stopColor='#5c18e2'
                    />
                    <Stop
                        offset={0.07}
                        stopColor='#5c18e2'
                    />
                    <Stop
                        offset={0.07}
                        stopColor='#5c19e1'
                    />
                    <Stop
                        offset={0.08}
                        stopColor='#5c19e1'
                    />
                    <Stop
                        offset={0.08}
                        stopColor='#5c19e0'
                    />
                    <Stop
                        offset={0.09}
                        stopColor='#5c19e0'
                    />
                    <Stop
                        offset={0.09}
                        stopColor='#5b19df'
                    />
                    <Stop
                        offset={0.09}
                        stopColor='#5b19df'
                    />
                    <Stop
                        offset={0.1}
                        stopColor='#5b19de'
                    />
                    <Stop
                        offset={0.1}
                        stopColor='#5b19de'
                    />
                    <Stop
                        offset={0.11}
                        stopColor='#5b19dd'
                    />
                    <Stop
                        offset={0.11}
                        stopColor='#5b19dd'
                    />
                    <Stop
                        offset={0.11}
                        stopColor='#5b19dc'
                    />
                    <Stop
                        offset={0.12}
                        stopColor='#5b19dc'
                    />
                    <Stop
                        offset={0.12}
                        stopColor='#5a19db'
                    />
                    <Stop
                        offset={0.13}
                        stopColor='#5a1adb'
                    />
                    <Stop
                        offset={0.13}
                        stopColor='#5a1ada'
                    />
                    <Stop
                        offset={0.13}
                        stopColor='#5a1ada'
                    />
                    <Stop
                        offset={0.14}
                        stopColor='#5a1ad9'
                    />
                    <Stop
                        offset={0.14}
                        stopColor='#5a1ad9'
                    />
                    <Stop
                        offset={0.14}
                        stopColor='#5a1ad8'
                    />
                    <Stop
                        offset={0.15}
                        stopColor='#5a1ad8'
                    />
                    <Stop
                        offset={0.15}
                        stopColor='#5a1ad7'
                    />
                    <Stop
                        offset={0.16}
                        stopColor='#591ad7'
                    />
                    <Stop
                        offset={0.16}
                        stopColor='#591ad6'
                    />
                    <Stop
                        offset={0.16}
                        stopColor='#591ad6'
                    />
                    <Stop
                        offset={0.17}
                        stopColor='#591ad5'
                    />
                    <Stop
                        offset={0.17}
                        stopColor='#591bd4'
                    />
                    <Stop
                        offset={0.18}
                        stopColor='#591bd4'
                    />
                    <Stop
                        offset={0.18}
                        stopColor='#591bd3'
                    />
                    <Stop
                        offset={0.18}
                        stopColor='#591bd3'
                    />
                    <Stop
                        offset={0.19}
                        stopColor='#591bd2'
                    />
                    <Stop
                        offset={0.19}
                        stopColor='#581bd2'
                    />
                    <Stop
                        offset={0.2}
                        stopColor='#581bd1'
                    />
                    <Stop
                        offset={0.2}
                        stopColor='#581bd1'
                    />
                    <Stop
                        offset={0.2}
                        stopColor='#581bd0'
                    />
                    <Stop
                        offset={0.21}
                        stopColor='#581bd0'
                    />
                    <Stop
                        offset={0.21}
                        stopColor='#581bcf'
                    />
                    <Stop
                        offset={0.21}
                        stopColor='#581bcf'
                    />
                    <Stop
                        offset={0.22}
                        stopColor='#581cce'
                    />
                    <Stop
                        offset={0.22}
                        stopColor='#571cce'
                    />
                    <Stop
                        offset={0.23}
                        stopColor='#571ccd'
                    />
                    <Stop
                        offset={0.23}
                        stopColor='#571ccd'
                    />
                    <Stop
                        offset={0.23}
                        stopColor='#571ccc'
                    />
                    <Stop
                        offset={0.24}
                        stopColor='#571ccc'
                    />
                    <Stop
                        offset={0.24}
                        stopColor='#571ccb'
                    />
                    <Stop
                        offset={0.25}
                        stopColor='#571ccb'
                    />
                    <Stop
                        offset={0.25}
                        stopColor='#571cca'
                    />
                    <Stop
                        offset={0.25}
                        stopColor='#571cca'
                    />
                    <Stop
                        offset={0.26}
                        stopColor='#561cc9'
                    />
                    <Stop
                        offset={0.26}
                        stopColor='#561cc9'
                    />
                    <Stop
                        offset={0.27}
                        stopColor='#561dc8'
                    />
                    <Stop
                        offset={0.27}
                        stopColor='#561dc8'
                    />
                    <Stop
                        offset={0.27}
                        stopColor='#561dc7'
                    />
                    <Stop
                        offset={0.28}
                        stopColor='#561dc7'
                    />
                    <Stop
                        offset={0.28}
                        stopColor='#561dc6'
                    />
                    <Stop
                        offset={0.29}
                        stopColor='#561dc6'
                    />
                    <Stop
                        offset={0.29}
                        stopColor='#551dc5'
                    />
                    <Stop
                        offset={0.29}
                        stopColor='#551dc5'
                    />
                    <Stop
                        offset={0.3}
                        stopColor='#551dc4'
                    />
                    <Stop
                        offset={0.3}
                        stopColor='#551dc4'
                    />
                    <Stop
                        offset={0.3}
                        stopColor='#551dc3'
                    />
                    <Stop
                        offset={0.31}
                        stopColor='#551dc3'
                    />
                    <Stop
                        offset={0.31}
                        stopColor='#551dc2'
                    />
                    <Stop
                        offset={0.32}
                        stopColor='#551ec1'
                    />
                    <Stop
                        offset={0.32}
                        stopColor='#551ec1'
                    />
                    <Stop
                        offset={0.32}
                        stopColor='#541ec0'
                    />
                    <Stop
                        offset={0.33}
                        stopColor='#541ec0'
                    />
                    <Stop
                        offset={0.33}
                        stopColor='#541ebf'
                    />
                    <Stop
                        offset={0.34}
                        stopColor='#541ebf'
                    />
                    <Stop
                        offset={0.34}
                        stopColor='#541ebe'
                    />
                    <Stop
                        offset={0.34}
                        stopColor='#541ebe'
                    />
                    <Stop
                        offset={0.35}
                        stopColor='#541ebd'
                    />
                    <Stop
                        offset={0.35}
                        stopColor='#541ebd'
                    />
                    <Stop
                        offset={0.36}
                        stopColor='#541ebc'
                    />
                    <Stop
                        offset={0.36}
                        stopColor='#531ebc'
                    />
                    <Stop
                        offset={0.36}
                        stopColor='#531fbb'
                    />
                    <Stop
                        offset={0.37}
                        stopColor='#531fbb'
                    />
                    <Stop
                        offset={0.37}
                        stopColor='#531fba'
                    />
                    <Stop
                        offset={0.38}
                        stopColor='#531fba'
                    />
                    <Stop
                        offset={0.38}
                        stopColor='#531fb9'
                    />
                    <Stop
                        offset={0.38}
                        stopColor='#531fb9'
                    />
                    <Stop
                        offset={0.39}
                        stopColor='#531fb8'
                    />
                    <Stop
                        offset={0.39}
                        stopColor='#521fb8'
                    />
                    <Stop
                        offset={0.39}
                        stopColor='#521fb7'
                    />
                    <Stop
                        offset={0.4}
                        stopColor='#521fb7'
                    />
                    <Stop
                        offset={0.4}
                        stopColor='#521fb6'
                    />
                    <Stop
                        offset={0.41}
                        stopColor='#521fb6'
                    />
                    <Stop
                        offset={0.41}
                        stopColor='#5220b5'
                    />
                    <Stop
                        offset={0.41}
                        stopColor='#5220b5'
                    />
                    <Stop
                        offset={0.42}
                        stopColor='#5220b4'
                    />
                    <Stop
                        offset={0.42}
                        stopColor='#5220b4'
                    />
                    <Stop
                        offset={0.43}
                        stopColor='#5120b3'
                    />
                    <Stop
                        offset={0.43}
                        stopColor='#5120b3'
                    />
                    <Stop
                        offset={0.43}
                        stopColor='#5120b2'
                    />
                    <Stop
                        offset={0.44}
                        stopColor='#5120b2'
                    />
                    <Stop
                        offset={0.44}
                        stopColor='#5120b1'
                    />
                    <Stop
                        offset={0.45}
                        stopColor='#5120b1'
                    />
                    <Stop
                        offset={0.45}
                        stopColor='#5120b0'
                    />
                    <Stop
                        offset={0.45}
                        stopColor='#5120b0'
                    />
                    <Stop
                        offset={0.46}
                        stopColor='#5121af'
                    />
                    <Stop
                        offset={0.46}
                        stopColor='#5021ae'
                    />
                    <Stop
                        offset={0.46}
                        stopColor='#5021ae'
                    />
                    <Stop
                        offset={0.47}
                        stopColor='#5021ad'
                    />
                    <Stop
                        offset={0.47}
                        stopColor='#5021ad'
                    />
                    <Stop
                        offset={0.48}
                        stopColor='#5021ac'
                    />
                    <Stop
                        offset={0.48}
                        stopColor='#5021ac'
                    />
                    <Stop
                        offset={0.48}
                        stopColor='#5021ab'
                    />
                    <Stop
                        offset={0.49}
                        stopColor='#5021ab'
                    />
                    <Stop
                        offset={0.49}
                        stopColor='#4f21aa'
                    />
                    <Stop
                        offset={0.5}
                        stopColor='#4f21aa'
                    />
                    <Stop
                        offset={0.5}
                        stopColor='#4f21a9'
                    />
                    <Stop
                        offset={0.5}
                        stopColor='#4f21a9'
                    />
                    <Stop
                        offset={0.51}
                        stopColor='#4f22a8'
                    />
                    <Stop
                        offset={0.51}
                        stopColor='#4f22a8'
                    />
                    <Stop
                        offset={0.52}
                        stopColor='#4f22a7'
                    />
                    <Stop
                        offset={0.52}
                        stopColor='#4f22a7'
                    />
                    <Stop
                        offset={0.52}
                        stopColor='#4f22a6'
                    />
                    <Stop
                        offset={0.53}
                        stopColor='#4e22a6'
                    />
                    <Stop
                        offset={0.53}
                        stopColor='#4e22a5'
                    />
                    <Stop
                        offset={0.54}
                        stopColor='#4e22a5'
                    />
                    <Stop
                        offset={0.54}
                        stopColor='#4e22a4'
                    />
                    <Stop
                        offset={0.54}
                        stopColor='#4e22a4'
                    />
                    <Stop
                        offset={0.55}
                        stopColor='#4e22a3'
                    />
                    <Stop
                        offset={0.55}
                        stopColor='#4e22a3'
                    />
                    <Stop
                        offset={0.55}
                        stopColor='#4e23a2'
                    />
                    <Stop
                        offset={0.56}
                        stopColor='#4d23a2'
                    />
                    <Stop
                        offset={0.56}
                        stopColor='#4d23a1'
                    />
                    <Stop
                        offset={0.57}
                        stopColor='#4d23a1'
                    />
                    <Stop
                        offset={0.57}
                        stopColor='#4d23a0'
                    />
                    <Stop
                        offset={0.57}
                        stopColor='#4d23a0'
                    />
                    <Stop
                        offset={0.58}
                        stopColor='#4d239f'
                    />
                    <Stop
                        offset={0.58}
                        stopColor='#4d239f'
                    />
                    <Stop
                        offset={0.59}
                        stopColor='#4d239e'
                    />
                    <Stop
                        offset={0.59}
                        stopColor='#4d239e'
                    />
                    <Stop
                        offset={0.59}
                        stopColor='#4c239d'
                    />
                    <Stop
                        offset={0.6}
                        stopColor='#4c239c'
                    />
                    <Stop
                        offset={0.6}
                        stopColor='#4c249c'
                    />
                    <Stop
                        offset={0.61}
                        stopColor='#4c249b'
                    />
                    <Stop
                        offset={0.61}
                        stopColor='#4c249b'
                    />
                    <Stop
                        offset={0.61}
                        stopColor='#4c249a'
                    />
                    <Stop
                        offset={0.62}
                        stopColor='#4c249a'
                    />
                    <Stop
                        offset={0.62}
                        stopColor='#4c2499'
                    />
                    <Stop
                        offset={0.63}
                        stopColor='#4c2499'
                    />
                    <Stop
                        offset={0.63}
                        stopColor='#4b2498'
                    />
                    <Stop
                        offset={0.63}
                        stopColor='#4b2498'
                    />
                    <Stop
                        offset={0.64}
                        stopColor='#4b2497'
                    />
                    <Stop
                        offset={0.64}
                        stopColor='#4b2497'
                    />
                    <Stop
                        offset={0.64}
                        stopColor='#4b2496'
                    />
                    <Stop
                        offset={0.65}
                        stopColor='#4b2596'
                    />
                    <Stop
                        offset={0.65}
                        stopColor='#4b2595'
                    />
                    <Stop
                        offset={0.66}
                        stopColor='#4b2595'
                    />
                    <Stop
                        offset={0.66}
                        stopColor='#4a2594'
                    />
                    <Stop
                        offset={0.66}
                        stopColor='#4a2594'
                    />
                    <Stop
                        offset={0.67}
                        stopColor='#4a2593'
                    />
                    <Stop
                        offset={0.67}
                        stopColor='#4a2593'
                    />
                    <Stop
                        offset={0.68}
                        stopColor='#4a2592'
                    />
                    <Stop
                        offset={0.68}
                        stopColor='#4a2592'
                    />
                    <Stop
                        offset={0.68}
                        stopColor='#4a2591'
                    />
                    <Stop
                        offset={0.69}
                        stopColor='#4a2591'
                    />
                    <Stop
                        offset={0.69}
                        stopColor='#4a2590'
                    />
                    <Stop
                        offset={0.7}
                        stopColor='#492590'
                    />
                    <Stop
                        offset={0.7}
                        stopColor='#49268f'
                    />
                    <Stop
                        offset={0.7}
                        stopColor='#49268f'
                    />
                    <Stop
                        offset={0.71}
                        stopColor='#49268e'
                    />
                    <Stop
                        offset={0.71}
                        stopColor='#49268e'
                    />
                    <Stop
                        offset={0.71}
                        stopColor='#49268d'
                    />
                    <Stop
                        offset={0.72}
                        stopColor='#49268d'
                    />
                    <Stop
                        offset={0.72}
                        stopColor='#49268c'
                    />
                    <Stop
                        offset={0.73}
                        stopColor='#48268c'
                    />
                    <Stop
                        offset={0.73}
                        stopColor='#48268b'
                    />
                    <Stop
                        offset={0.73}
                        stopColor='#48268b'
                    />
                    <Stop
                        offset={0.74}
                        stopColor='#48268a'
                    />
                    <Stop
                        offset={0.74}
                        stopColor='#482689'
                    />
                    <Stop
                        offset={0.75}
                        stopColor='#482789'
                    />
                    <Stop
                        offset={0.75}
                        stopColor='#482788'
                    />
                    <Stop
                        offset={0.75}
                        stopColor='#482788'
                    />
                    <Stop
                        offset={0.76}
                        stopColor='#482787'
                    />
                    <Stop
                        offset={0.76}
                        stopColor='#472787'
                    />
                    <Stop
                        offset={0.77}
                        stopColor='#472786'
                    />
                    <Stop
                        offset={0.77}
                        stopColor='#472786'
                    />
                    <Stop
                        offset={0.77}
                        stopColor='#472785'
                    />
                    <Stop
                        offset={0.78}
                        stopColor='#472785'
                    />
                    <Stop
                        offset={0.78}
                        stopColor='#472784'
                    />
                    <Stop
                        offset={0.79}
                        stopColor='#472784'
                    />
                    <Stop
                        offset={0.79}
                        stopColor='#472783'
                    />
                    <Stop
                        offset={0.79}
                        stopColor='#472883'
                    />
                    <Stop
                        offset={0.8}
                        stopColor='#462882'
                    />
                    <Stop
                        offset={0.8}
                        stopColor='#462882'
                    />
                    <Stop
                        offset={0.8}
                        stopColor='#462881'
                    />
                    <Stop
                        offset={0.81}
                        stopColor='#462881'
                    />
                    <Stop
                        offset={0.81}
                        stopColor='#462880'
                    />
                    <Stop
                        offset={0.82}
                        stopColor='#462880'
                    />
                    <Stop
                        offset={0.82}
                        stopColor='#46287f'
                    />
                    <Stop
                        offset={0.82}
                        stopColor='#46287f'
                    />
                    <Stop
                        offset={0.83}
                        stopColor='#45287e'
                    />
                    <Stop
                        offset={0.83}
                        stopColor='#45287e'
                    />
                    <Stop
                        offset={0.84}
                        stopColor='#45287d'
                    />
                    <Stop
                        offset={0.84}
                        stopColor='#45297d'
                    />
                    <Stop
                        offset={0.84}
                        stopColor='#45297c'
                    />
                    <Stop
                        offset={0.85}
                        stopColor='#45297c'
                    />
                    <Stop
                        offset={0.85}
                        stopColor='#45297b'
                    />
                    <Stop
                        offset={0.86}
                        stopColor='#45297b'
                    />
                    <Stop
                        offset={0.86}
                        stopColor='#45297a'
                    />
                    <Stop
                        offset={0.86}
                        stopColor='#44297a'
                    />
                    <Stop
                        offset={0.87}
                        stopColor='#442979'
                    />
                    <Stop
                        offset={0.87}
                        stopColor='#442979'
                    />
                    <Stop
                        offset={0.88}
                        stopColor='#442978'
                    />
                    <Stop
                        offset={0.88}
                        stopColor='#442977'
                    />
                    <Stop
                        offset={0.88}
                        stopColor='#442977'
                    />
                    <Stop
                        offset={0.89}
                        stopColor='#442976'
                    />
                    <Stop
                        offset={0.89}
                        stopColor='#442a76'
                    />
                    <Stop
                        offset={0.89}
                        stopColor='#432a75'
                    />
                    <Stop
                        offset={0.9}
                        stopColor='#432a75'
                    />
                    <Stop
                        offset={0.9}
                        stopColor='#432a74'
                    />
                    <Stop
                        offset={0.91}
                        stopColor='#432a74'
                    />
                    <Stop
                        offset={0.91}
                        stopColor='#432a73'
                    />
                    <Stop
                        offset={0.91}
                        stopColor='#432a73'
                    />
                    <Stop
                        offset={0.92}
                        stopColor='#432a72'
                    />
                    <Stop
                        offset={0.92}
                        stopColor='#432a72'
                    />
                    <Stop
                        offset={0.93}
                        stopColor='#432a71'
                    />
                    <Stop
                        offset={0.93}
                        stopColor='#422a71'
                    />
                    <Stop
                        offset={0.93}
                        stopColor='#422a70'
                    />
                    <Stop
                        offset={0.94}
                        stopColor='#422b70'
                    />
                    <Stop
                        offset={0.94}
                        stopColor='#422b6f'
                    />
                    <Stop
                        offset={0.95}
                        stopColor='#422b6f'
                    />
                    <Stop
                        offset={0.95}
                        stopColor='#422b6e'
                    />
                    <Stop
                        offset={0.95}
                        stopColor='#422b6e'
                    />
                    <Stop
                        offset={0.96}
                        stopColor='#422b6d'
                    />
                    <Stop
                        offset={0.96}
                        stopColor='#422b6d'
                    />
                    <Stop
                        offset={0.96}
                        stopColor='#412b6c'
                    />
                    <Stop
                        offset={0.97}
                        stopColor='#412b6c'
                    />
                    <Stop
                        offset={0.97}
                        stopColor='#412b6b'
                    />
                    <Stop
                        offset={0.98}
                        stopColor='#412b6b'
                    />
                    <Stop
                        offset={0.98}
                        stopColor='#412b6a'
                    />
                    <Stop
                        offset={0.98}
                        stopColor='#412c6a'
                    />
                    <Stop
                        offset={0.99}
                        stopColor='#412c69'
                    />
                    <Stop
                        offset={0.99}
                        stopColor='#412c69'
                    />
                    <Stop
                        offset={1}
                        stopColor='#402c68'
                    />
                    <Stop
                        offset={1}
                        stopColor='#402c68'
                    />
                </LinearGradient>
                <LinearGradient
                    id='linear-gradient-2'
                    x1={675.44}
                    y1={545.5}
                    x2={1106.42}
                    y2={927.46}
                    xlinkHref='#linear-gradient'
                />
                <LinearGradient
                    id='linear-gradient-3'
                    x1={761.9}
                    y1={447.95}
                    x2={1192.87}
                    y2={829.91}
                    xlinkHref='#linear-gradient'
                />
            </Defs>
            <Circle
                cx='500'
                cy='500'
                r='450'
                stroke='blue'
                strokeWidth='2.5'
                fill='#fff'
            />
            <Path
                d='M716.34 198.08c-93.8 5.3-189.6 37.1-269 89.4-32.8 21.6-56.4 40.6-83.4 67-83.6 81.9-137.8 184.2-158.6 299.9-5.5 30.3-7.9 59.3-7.9 95.6 0 29.8.9 45.6 4 69 19.2 147.8 94.6 279.3 211.7 369.4a566.58 566.58 0 00143.8 79.7c81.8 30.5 173.5 41.5 258.4 30.8 88.2-11 166.6-39.9 240.2-88.6 30.5-20.1 53.8-39 80.7-65.3 84.3-82.5 139.1-187.2 158.6-303a551.26 551.26 0 00-46.7-331c-69.9-145-196.5-250.8-352-294-58.14-16.2-117.14-22.4-179.8-18.9zm-164.8 430.1c-.3 1.8-1.7 9.6-3.1 17.3a437.34 437.34 0 00-6.2 53.5c-.8 13.8-.8 13.8-5.4-3.7-10.3-39.2-23.4-57.1-44.9-61.4-5.1-1-6.4-1-7.1.1-.4.7-1.8 7.3-2.9 14.8-8.1 50.6-8.7 111.1-1.5 161.7 1.5 10.9 5 30.4 6 33.7.5 1.7-1.6 1.8-34.5 1.8-28.7 0-35.1-.2-35.1-1.3 0-.8.9-5.6 2-10.8 2.1-10.3 5.3-31.7 7-47.4s2.4-67.6 1.1-87.5c-2.2-32.1-7.1-66-9.7-66-3.2 0-12.2 2.4-15.9 4.2-16.1 8.1-28 28.7-36.6 63.8l-2.3 9.5-.7-6.5c-.4-3.6-1.3-13-1.9-21-1.2-15.2-3.8-34.4-6.5-46.8a85.14 85.14 0 01-1.5-9.3c0-1.9 1.8-1.9 100.1-1.9h100.2zm74.3-2c0 .7-1.1 6.9-2.4 13.8-5.4 28.2-7.7 57.6-7.9 102.5-.2 29.2 0 32.8 1.9 41.5 5.1 22.7 15.1 38.8 29.4 47.4 25.1 15.2 53 6.1 66.4-21.6 9-18.7 11.1-32.3 10.3-68.3-1.3-59.2-9.4-89.5-29.5-110.8l-5.5-5.7h32.1c17.7 0 32.2.2 32.2.5a61 61 0 01-3.3 5.7c-12 18.9-17.7 54.5-17.7 111.3 0 35.6-2.6 51.6-11.2 69.5-4.3 9-6.2 11.7-13.3 18.8-12.9 12.9-26.9 18.6-48.5 19.9-43.2 2.4-80-25.8-89.5-68.7-1.2-5.7-1.8-16.6-2.5-45.5-1.2-48.8-3.4-74.6-8.9-101-1-5-1.7-9.3-1.4-9.8s15.9-.7 34.9-.7c26.8.02 34.4.3 34.4 1.2zm235.7-.2c31.8 2.2 55.2 11.1 71.3 27.3 12.6 12.5 18.5 26.3 18.4 42.7-.1 25.1-14.8 46.7-41 60.2-18.5 9.6-35.3 12.8-66.6 12.8-16 0-20.8.3-20.8 1.2.1 9.7 4.4 45.2 7.6 62.2 1.3 7.1 2.4 13 2.4 13.2s-15.8.4-35.1.4h-35.1l.6-2.3c1.5-5.7 6.7-39.8 8.1-53.7 2.3-21.6 3.1-66.3 1.6-89-1.4-21.8-4.3-45.8-7.6-62.5-1.2-6.6-2.1-12.3-1.8-12.8.6-1 81.3-.8 98 .32zm211.3 1.3c34.2 5.8 58.3 20.9 69 43.2 4.5 9.4 6 15.9 6 25.8-.1 28.4-20.9 54-53.1 65.3-16.1 5.6-22.6 6.6-49.6 7.1l-25.3.5v4.9c0 11.3 4.6 47.5 8.3 65.1l1.5 6.8H959l1.5-6.8c7.6-36.5 11.3-86.3 9.4-127.1-1.3-26.1-4.1-52.5-7.6-71.8-1.4-7.3-2.5-13.8-2.5-14.4.04-1.88 100.84-.6 113.04 1.4z'
                transform='translate(-197.44 -197.13)'
                fill='url(#linear-gradient)'
            />
            <Path
                d='M850 635.18c-9.5 3.2-19.1 17.6-23 34.5-3.6 15-4.3 23.7-4.9 57.5l-.6 32.8h15.2c12.6 0 16.2-.3 21.2-2 25.4-8.6 42.2-37.3 40.6-69.4-1.2-24.1-11-44.1-25.1-51.3-5.76-3-17.66-4-23.4-2.1z'
                transform='translate(-197.44 -197.13)'
                fill='url(#linear-gradient)'
            />
            <Path
                d='M1046.54 635.38c-13 4.8-20.9 19.3-25.8 47.6-.6 3.6-1.4 22.4-1.6 41.8l-.5 35.4 16.9-.4 16.9-.3 7.9-3.9c13.9-6.9 24.8-20 30.6-36.8 7.2-21 5.3-46.5-4.9-65.1-3.5-6.4-11-13.9-16.8-16.7s-17.24-3.7-22.7-1.6z'
                transform='translate(-197.44 -197.13)'
                fill='url(#linear-gradient)'
            />
        </Svg>
    );
}

export default SvgComponent;
